sudo: false
language: node_js
node_js:
  - 10
  - 'stable'
cache:
  directories:
    - node_modules
script:
  - npm run build
  - npm test
jobs:
  include:
    - stage: release gh-pages
      script:
        - echo "Deploying to GitHub pages ..."
        - npm run build
      deploy:
        provider: pages
        skip_cleanup: true # prevents travis from cleaning build files
        github_token: $GITHUB_TOKEN
        local_dir: build # deployment folder
        target_branch: gh-pages
        keep_history: false # force push
        on:
          branch: master
          # tags: true
